baseURL = "http://acassaigne.info/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "fr"
# language code
languageCode = "en"
title = "Anthony Cassaigne blog"

enableRobotsTXT = true

enableGitInfo = true

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"

[params.list]
    # special amount of posts in each list page
    paginate = 5
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

[params.social]
twitter = "@acassaigne"


[author]
  name = "Anthony Cassaigne"
  email = ""
  link = ""

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[languages.fr]
  [languages.fr.params.home]
        # amount of RSS pages
        rss = 10
        # Home page profile
        [languages.fr.params.home.profile]
          enable = true
          # Gravatar Email for preferred avatar in home page
          gravatarEmail = ""
          # URL of avatar shown in home page
          #avatarURL = "avataaars.png"
          # title shown in home page (HTML format is supported)
          title = "Anthony Cassaigne"
          # subtitle shown in home page
          subtitle = "Agilité & Craft Code"
          # whether to use typeit animation for subtitle
          typeit = true
          # whether to show social links
          social = true
          # disclaimer (HTML format is supported)
          disclaimer = ""
        # Home page posts
        [languages.fr.params.home.posts]
          enable = true
          # special amount of posts in each home posts page
          paginate = 5
      # Social config in home page
      [languages.fr.params.social]
        GitHub = "acassaigne"
        #Linkedin = "xxxx"
        Twitter = "@acassaigne"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
#  [[menu.main]]
#    identifier = "categories"
#    pre = ""
#    post = ""
#    name = "Categories"
#    url = "/categories/"
#    title = ""
#    weight = 3


[params.footer]
    enable = true
    # Custom content (HTML format is supported)
    custom = ''
    # whether to show Hugo and theme info
    hugo = true
    # whether to show copyright info
    copyright = false
    # whether to show the author
    author = true
    # site creation time
    since = 2019
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">CC BY-SA 4.0</a>'



# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
